### ISSUE TITLE
ETS2 Crashes through the launcher

### ISSUE THREAD

**Issue by Leinuu** [lhark/truckersmp-cli#16] opened 2018-02-18 10:34 UTC
ETS2 Crashes through the launcher, but when the game is launched through steam, it works fine.

Here is the dump that it gave me
>Crash log created on: Sun Feb 18 11:42:18 2018
AvailMEM Virt:134217727 Phys:1141 Total:2681
TotalMEM Virt:134217727 Phys:3904 Total:5952
Exception code: C0000005 ACCESS_VIOLATION
EXE Base address: 0000000140000000
Fault address: 0000000140B69603 0001:00B68603 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
Registers:
RAX:0000000000000000
RBX:000000000023F410
RCX:000000014128FA20
RDX:0000000000000000
RSI:0000000000000000
RDI:000000000023F360
R8:0000000000000000
R9:0000000140FFAD88
R10:00000000032AF9D0
R11:000000000023F5B0
R12:0000000140FFAD88
R13:0000000140FFAD88
R14:FFFFFFFFFFFFFFFF
R15:000000014128FA20
CS:RIP: 0033:0000000140B69603
SS:RSP: 002B:000000000023F2D0 RBP:000000000023F4C9
DS:0000  ES:0000  FS:0000  GS:0000
Flags: 00010246
RIP preamble: 30 41 5E 5F 5E C3 CC CC CC CC CC CC CC 48 89 5C
              24 18 48 89 74 24 20 57 41 54 41 55 41 56 41 57
              48 83 EC 30 48 8B 01 4D 8B F1 4C 89 4C 24 20 4D
              8B E0 48 8B FA 4D 8B C8 45 33 C0 33 D2 4C 8B F9
RIP bytecode: FF 10 45 33 ED 48 8B F0 48 83 F8 FF 0F 84 BF 00
              00 00 48 89 6C 24 68 E8 91 DD FE FF 48 8D 0C 75
              02 00 00 00 E8 6C BF 21 00 48 8B E8 48 85 C0 74
              2B 41 8D 4D 18 66 44 89 2C 70 E8 3A 71 21 00 48
Call stack (IMH):
Address           Frame
0000000140B69603  000000000023F4C9  0001:00B68603 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
0000000140B57457  000000000023F4C9  0001:00B56457 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001408CFC9B  000000000023F4C9  0001:008CEC9B C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001408CFD9B  000000000023F4C9  0001:008CED9B C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
0000000140B842B6  000000000023F4C9  0001:00B832B6 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
0000000140B54B3C  000000000023FBC0  0001:00B53B3C C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
0000000140B54D80  000000000023FBC0  0001:00B53D80 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001408CF10F  000000000023FBC0  0001:008CE10F C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001400FB7DC  000000000023FBC0  0001:000FA7DC C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001400FC119  000000000023FBC0  0001:000FB119 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
00000001400602EA  000000000023FBC0  0001:0005F2EA C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
0000000180506E84  000000000023FBC0  0001:00505E84 Z:\home\lain\Desktop\truckersmp-cli\truckersmp\core_ets2mp.dll
Call stack (RTL):
Address           Logical addr  Module
Stack:
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00 6F 00 6D 00 6D 00 6F 00
  20 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00 A0 F2 23 00 00 00 00 00 D6 64 C7 7B 00 00 00 00
  00 00 00 00 00 00 00 00 08 8C 5B 03 00 00 00 00 F8 00 00 00 00 00 00 00 F0 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 60 F3 23 00 00 00 00 00 C9 F4 23 00 00 00 00 00 03 96 B6 40 01 00 00 00
  90 F3 23 00 00 00 00 00 DA 95 C7 7B 00 00 00 00 00 00 00 00 00 00 00 00 57 00 00 00 00 00 00 00
  A0 F2 23 00 00 00 00 00 62 05 CA 7B 00 00 00 00 20 F3 23 00 00 00 00 00 10 8C 5B 03 00 00 00 00
  08 8C 5B 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C6 02 00 00 00 00 00 2D CD D2 D6 63 16 C2
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00 80 29 23 41 01 00 00 00 68 7B 8E 40 01 00 00 00
  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 80 2C 23 41 01 00 00 00 60 41 00 03 00 00 00 00
  88 AD FF 40 01 00 00 00 00 00 00 00 00 00 00 00 B0 F3 23 00 00 00 00 00 57 74 B5 40 01 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 F4 23 00 00 00 00 00 00 00 00 00 00 00 00 00
  68 F3 23 00 00 00 00 00 F0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 77 00 00 00 00 00 00 00
  88 AD FF 40 01 00 00 00 9B FC 8C 40 01 00 00 00 10 F4 23 00 00 00 00 00 01 00 00 00 00 00 00 00
  F0 F5 23 00 00 00 00 00 14 48 D2 40 01 00 00 00 00 00 00 00 01 00 00 00 FE FF FF FF FF FF FF FF
  80 2C 23 41 01 00 00 00 00 00 C6 02 00 00 00 00 C8 F4 23 00 00 00 00 00 9B FD 8C 40 01 00 00 00
  70 00 23 41 01 00 00 00 68 7B 8E 40 01 00 00 00 80 2C 23 41 01 00 00 00 38 B3 26 41 01 00 00 00
  FE FF FF FF FF FF FF FF 00 2D CD D2 D6 63 16 C2 01 00 00 00 00 00 00 00 B6 42 B8 40 01 00 00 00
  C8 F4 23 00 00 00 00 00 C0 2F 23 41 01 00 00 00 00 00 00 00 00 00 00 00 8D F8 8C 40 01 00 00 00
  00 00 00 00 00 00 00 00 F0 00 00 00 00 00 00 00 08 03 00 00 00 00 00 00 A8 00 01 00 00 00 00 00
  B0 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C6 02 00 00 00 00 00 2D CD D2 D6 63 16 C2
  76 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00 6F 00 6D 00 6D 00 6F 00 20 20 20 00 00 00 00 00
  00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 F0 EA FF FF 7F 00 00 C0 FB 23 00 00 00 00 00 3C 4B B5 40 01 00 00 00
  00 F0 EA FF FF 7F 00 00 00 86 5B 03 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
  C0 FB 23 00 00 00 00 00 AC 47 D2 40 01 00 00 00 F0 F5 23 00 00 00 00 00 BF F4 8C 40 01 00 00 00
  F0 F5 23 00 00 00 00 00 76 00 00 00 00 00 00 00 F0 F5 23 00 00 00 00 00 D4 EA 8C 40 01 00 00 00
  00 00 00 00 00 00 00 00 82 EA 8C 40 01 00 00 00 F0 F5 23 00 00 00 00 00 00 00 00 00 00 00 00 00
  FE FF FF FF FF FF FF FF 38 B3 26 41 01 00 00 00 68 86 5B 03 00 00 00 00 8E 4F B5 40 01 00 00 00
  68 86 5B 03 00 00 00 00 68 86 5B 03 00 00 00 00 C0 FB 23 00 00 00 00 00 01 00 00 00 00 00 00 00
  00 00 5B 03 00 00 00 00 0F 29 B5 40 01 00 00 00 00 00 00 00 00 00 00 00 07 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 80 4D B5 40 01 00 00 00
  00 86 5B 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 F0 EA FF FF 7F 00 00
  00 00 00 00 00 00 00 00 0F F1 8C 40 01 00 00 00 01 00 00 00 00 00 00 00 00 86 5B 03 00 00 00 00
  C0 FB 23 00 00 00 00 00 00 00 00 00 00 00 00 00 FE FF FF FF FF FF FF FF D6 64 C7 7B 00 00 00 00
  18 00 00 00 00 00 00 00 DC B7 0F 40 01 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  03 00 00 00 00 00 00 00 80 E6 25 41 01 00 00 00 10 F8 23 00 00 00 00 00 02 00 00 00 00 00 00 00
  70 F7 23 00 00 00 00 00 D6 64 C7 7B 00 00 00 00 00 00 00 00 00 00 00 00 38 85 5B 03 00 00 00 00
  38 00 00 00 00 00 00 00 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 24 6D C7 7B 00 00 00 00
  60 F8 23 00 00 00 00 00 02 00 00 00 00 00 00 00 60 F8 23 00 00 00 00 00 DA 95 C7 7B 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 40 85 5B 03 00 00 00 00 38 85 5B 03 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 C6 02 00 00 00 00 00 2D CD D2 D6 63 16 C2 FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00
  6F 00 6D 00 6D 00 6F 00 20 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF
  FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 BF 23 41 01 00 00 00
  80 E6 25 41 01 00 00 00 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 F9 23 00 00 00 00 00 4E 1B C6 7B 00 00 00 00
  70 15 01 00 00 00 00 00 40 C7 23 41 01 00 00 00 B0 F8 23 00 00 00 00 00 00 2D CD D2 D6 63 16 C2
  80 E6 25 41 01 00 00 00 0E 00 00 00 00 00 00 00 C0 F9 23 00 00 00 00 00 00 00 00 00 00 00 00 00
  50 21 EE 40 01 00 00 00 E9 FD 00 00 00 00 00 00 04 01 00 00 00 00 00 00 15 88 46 7B 00 00 00 00
  00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00
  6F 00 6D 00 6D 00 6F 00 20 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF
  FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 C7 23 41 01 00 00 00
  80 E6 25 41 01 00 00 00 18 00 00 00 00 00 00 00 00 F0 EA FF FF 7F 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 FB 23 00 00 00 00 00 5E 21 EE 40 01 00 00 00
  00 00 00 00 00 00 00 00 57 CE 09 40 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 80 E6 25 41 01 00 00 00 C0 FB 23 00 00 00 00 00 19 C1 0F 40 01 00 00 00
  03 00 00 00 00 00 00 00 00 F0 EA FF FF 7F 00 00 03 00 00 00 00 00 00 00 18 00 00 00 00 00 00 00
  18 00 00 00 00 00 00 00 EA 02 06 40 01 00 00 00 03 00 00 00 00 00 00 00 B0 74 E5 40 01 00 00 00
  03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 B0 74 E5 40 01 00 00 00 68 76 E5 40 01 00 00 00
  A1 C5 C0 B1 62 7F 00 00 84 6E 50 80 01 00 00 00 00 00 00 00 00 00 00 00 0A 00 00 00 00 00 00 00
  65 00 73 00 5C 00 43 00 6F 00 6D 00 6D 00 6F 00 30 02 06 40 01 00 00 00 60 E4 23 00 00 00 00 00
  FF FF FF FF FF FF FF FF F0 8A 50 80 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  79 D8 06 00 00 00 00 00 0A 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  F0 FB 05 40 01 00 00 00 00 00 00 00 00 00 00 00 A0 FB 23 00 00 00 00 00 3E 2B D2 40 01 00 00 00
  C8 FB 23 00 00 00 00 00 A0 FB 23 00 00 00 00 00 F0 FB 05 40 01 00 00 00 88 FB 23 00 00 00 00 00
  90 21 00 00 00 00 00 00 96 2F D2 40 01 00 00 00 30 67 E1 40 01 00 00 00 00 00 00 00 00 00 00 00
  8E 21 00 00 00 00 00 00 C8 FB 23 00 00 00 00 00 02 00 00 00 00 00 00 00 B0 FB 23 00 00 00 00 00
  70 FD 23 00 00 00 00 00 A6 A7 D1 40 01 00 00 00 8F 21 00 00 00 00 00 00 BD A1 D1 40 01 00 00 00
  04 00 00 00 00 00 00 00 1C C9 D2 40 01 00 00 00 79 D8 06 00 00 00 00 00 0A 00 00 00 00 00 00 00
  E0 FB 23 00 00 00 00 00 22 00 00 00 00 00 00 00 70 FD 23 00 00 00 00 00 00 00 00 00 00 00 00 00
  A1 C5 C0 B1 62 7F 00 00 C0 FB 23 00 00 00 00 00 00 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00
  80 84 5B 03 00 00 00 00 C0 FB 23 00 00 00 00 00 00 F0 EA FF FF 7F 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0A 00 00 00 00 00 00 00 70 FD 23 00 00 00 00 00
  A1 C5 C0 B1 62 7F 00 00 00 00 00 00 00 00 00 00 00 C3 3F 41 01 00 00 00 10 C3 3F 41 01 00 00 00
  00 00 00 00 00 00 00 00 E7 F1 47 7B 00 00 00 00 10 C3 3F 41 01 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2D CD D2 D6 63 16 C2
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  65 00 73 00 5C 00 43 00 6F 00 6D 00 6D 00 6F 00 20 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00
  FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 EA FF FF 7F 00 00 00 00 00 00 00 00 00 00
  D0 FF 23 00 00 00 00 00 E3 A8 CB 7B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 8A A8 CB 7B 00 00 00 00 00 00 00 00 00 00 00 00 F0 FD 23 00 00 00 00 00
  D0 FD 23 00 00 00 00 00 00 80 EA FF FF 7F 00 00 F0 F0 47 7B 00 00 00 00 10 C3 3F 41 01 00 00 00
  FF FF FF FF FF FF FF FF A0 04 CE 7B 00 00 00 00 D0 05 45 7B 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 0B E0 CE 45 C1 CE C8 E7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0B E0 2E 41 C1 CE C8 E7 0B E0 7A EB 11 39 C8 E7
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2D CD D2 D6 63 16 C2
  00 00 00 00 00 00 00 00 CA 30 CB 7B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  D0 FF 23 00 00 00 00 00 99 53 CB 7B 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 65 00 73 00 5C 00 43 00 6F 00 6D 00 6D 00 6F 00
  20 20 20 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 FF
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2E 2F 74 72 75 63 6B 65 72 73 6D 70 5C 63 6F 72
  65 5F 65 74 73 32 6D 70 2E 64 6C 6C 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Modules:
0000000140000000 01421000 00000001413FC310 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe
000000007BC40000 0010C000 000000007BCE02E0 C:\windows\system32\ntdll.dll
000000007B420000 00401000 000000007B4AD010 C:\windows\system32\KERNEL32.dll
0000000180000000 00D01000 0000000180CFDBB0 Z:\home\lain\Desktop\truckersmp-cli\truckersmp\core_ets2mp.dll
00007F62AF940000 0028A000 00007F62AF99D300 C:\windows\system32\advapi32.dll
00007F62AF540000 002F1000 00007F62AF57BE00 C:\windows\system32\comdlg32.dll
00007F62AF030000 00507000 00007F62AF0E9AE0 C:\windows\system32\shell32.dll
00007F62AED90000 00283000 00007F62AEDDD710 C:\windows\system32\shlwapi.dll
00007F62AE950000 0042C000 00007F62AEA0E1E0 C:\windows\system32\user32.dll
00007F62AE5D0000 00362000 00007F62AE66AD80 C:\windows\system32\gdi32.dll
00007F62AE3A0000 00210000 00007F62AE3ACB20 C:\windows\system32\version.dll
00007F62AE180000 00216000 00007F62AE18DDC0 C:\windows\system32\aclui.dll
00007F62ADE50000 0032B000 00007F62ADEF4380 C:\windows\system32\comctl32.dll
00007F62ADC00000 00243000 00007F62ADC2C270 C:\windows\system32\winspool.drv
00007F62AD9F0000 00209000 00007F62AD9F7900 C:\windows\system32\normaliz.dll
00007F62AD660000 00386000 00007F62AD754C00 C:\windows\system32\ole32.dll
00007F62AD3A0000 00290000 00007F62AD3FC230 C:\windows\system32\rpcrt4.dll
00007F62AD120000 00274000 00007F62AD15FE30 C:\windows\system32\setupapi.dll
000000003B400000 00037000 000000003B408624 C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\steam_api64.dll
00007F62ACE50000 002C1000 00007F62ACE83EB0 C:\windows\system32\winmm.dll
00007F62ACBF0000 0025A000 00007F62ACC24E80 C:\windows\system32\wldap32.dll
00007F62A4FD0000 00239000 00007F62A4FF9810 C:\windows\system32\ws2_32.dll
00007F62A4DB0000 00217000 00007F62A4DBE8F0 C:\windows\system32\imm32.dll
00007F62A4B10000 0028F000 00007F62A4B63D00 C:\windows\system32\winex11.drv
00007F62A23D0000 00239000 00007F62A23F08E0 C:\windows\system32\uxtheme.dll
00007F629FF20000 00212000 00007F629FF2FD40 C:\windows\system32\api-ms-win-core-synch-l1-2-0.dll
00007F629FD10000 0020E000 00007F629FD1C7B0 C:\windows\system32\api-ms-win-core-fibers-l1-1-1.dll
00007F629FB00000 0020B000 00007F629FB08DC0 C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
00007F629F8C0000 00237000 00007F629F8E80D0 C:\windows\system32\secur32.dll
00007F629F690000 0022A000 00007F629F6AAB00 C:\windows\system32\netapi32.dll
00007F629F460000 00225000 00007F629F4798E0 C:\windows\system32\iphlpapi.dll
00007F629F250000 00205000 00007F629F252B20 C:\windows\system32\api-ms-win-core-sysinfo-l1-2-1.dll
00007F629F030000 00211000 00007F629F03F890 C:\windows\system32\api-ms-win-core-file-l2-1-1.dll
00007F629ECC0000 0036E000 00007F629ED98440 C:\windows\system32\oleaut32.dll
00007F629EA90000 0020B000 00007F629EA989A0 C:\windows\system32\msimg32.dll
00007F629E7C0000 002C7000 00007F629E842730 C:\windows\system32\msvcrt.dll
0000000038000000 00DF6000 0000000038813D64 C:\Program Files (x86)\Steam\steamclient64.dll
00007F629E4C0000 002D9000 00007F629E529060 C:\windows\system32\crypt32.dll
00007F629E290000 0021A000 00007F629E2A4490 C:\windows\system32\bcrypt.dll
00007F629E070000 00219000 00007F629E083870 C:\windows\system32\imagehlp.dll
00007F629DE10000 0025D000 00007F629DE4ABD0 C:\windows\system32\dbghelp.dll
00007F629DBF0000 0020C000 00007F629DBFA9B0 C:\windows\system32\psapi.dll
000000003F000000 00372000 000000003F024DF8 C:\Program Files (x86)\Steam\tier0_s64.dll
000000003F600000 0006B000 000000003F6228F4 C:\Program Files (x86)\Steam\vstdlib_s64.dll
00007F629D9E0000 00209000 00007F629D9E6420 C:\windows\system32\mswsock.dll
00007F629D600000 00243000 00007F629D62B2A0 C:\windows\system32\usp10.dll
00007F629D3F0000 00206000 00007F629D3F3BF0 C:\windows\system32\api-ms-win-appmodel-runtime-l1-1-1.dll
00007F629CDD0000 00208000 00007F629CDD4660 C:\windows\system32\schannel.dll`

**Comment by lhark** [comment] 2018-02-18 17:32
I cannot reproduce the issue.

Can you provide the command you used to run the launcher and the full output of the launcher (everything between the command being run and the crash dump) ?

**Comment by Leinuu** [comment] 2018-02-18 21:18
The command was 
`./truckersmp-cli /home/lain/.wine/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Euro\ Truck\ Simulator\ 2/`

and before attempting to launch ETS2 it gave me this
>[23:17:14] <info> [p3api] Game version is supported. Base address: 0000000000000000 Signature: 98df145019dc
[23:17:14] <info> [net] [http async] Creating thread(s)[1]...
[23:17:14] <info> [net] [http async] Thread(s) created.
[23:17:14] <info> [client] Initialized successfully.

**Comment by lhark** [comment] 2018-02-18 23:26
Did **truckersmp-cli** not try to update the mod ? like so:
```
--2018-02-18 19:17:23--  https://update.ets2mp.com/files.json
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving update.ets2mp.com (update.ets2mp.com)... 104.24.114.213, 104.24.115.213, 2400:cb00:2048:1::6818:73d5, ...
Connecting to update.ets2mp.com (update.ets2mp.com)|104.24.114.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12413 (12K) [application/json]
Saving to: ‘STDOUT’

-                                   100%[==================================================================>]  12.12K  --.-KB/s    in 0s

2018-02-18 19:17:24 (79.7 MB/s) - written to stdout [12413/12413]
```

Also, could you try launching the game in steam by right-clicking on it and selecting "Launch with DirectX (64-bit)" or "Lauch with OpenGL (64-bit)" and then try **truckersmp-cli** once again.

Remember, in order for the mod to work correctly, your wine prefix must be configured to run 64-bit applications.

**Comment by Gnabbist** [comment] 2018-03-20 14:56
I had what appears to be the same problem as originally reported in this thread. The two key factors that fixed it for me were:
1. Moving to Wine 3.00 (from winehq)
2. Starting the trucksim in single player in OpenGL mode and closing it again, just before starting multiplayer via this script.

**Comment by lhark** [comment] 2018-03-20 15:31
Thank you for your feedback :)

In the absence of any answer from @Leinuu, I will close this issue for now.

**Closed by lhark** 2018-03-20 15:31 UTC
