### ISSUE TITLE
TruckersMP not starting after new update for 1.35

### ISSUE THREAD

**Issue by squadramunter** [lhark/truckersmp-cli#34] opened 2019-06-19 13:49 UTC
Hello I cannot play ETS2 anymore. It did work before but since version 1.35 from ETS2 and the new launcher from TruckersMP this script does not work anymore and give this error.

Do you know how you can fix this?

![ets2_fail](https://user-images.githubusercontent.com/26835124/59771335-c8f2e280-92a9-11e9-8360-3d08bd6f593e.png)

**Comment by Segelzwerg** [comment] 2019-06-20 13:29
I solved it by installing SteamVR in the Linux Steam App.

**Comment by squadramunter** [comment] 2019-06-20 17:03
> I solved it by installing SteamVR in the Linux Steam App.
> 
> EDIT: the pop-up still pops up. I thought the error was relating to `Proto: Missing or invalid openvrpaths.vrpath .....`

You you did not solve this problem yet?

**Comment by squadramunter** [comment] 2019-06-20 17:10
I got some more info regarding to this issue

`CApplicationManagerPopulateThread took 2 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
../steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (117) : Assertion Failed: SteamDatagramTransportLock held for 27.7ms!
assert_20190620190614_11.dmp[14742]: Uploading dump (out-of-process)
/tmp/dumps/assert_20190620190614_11.dmp
assert_20190620190614_11.dmp[14742]: Finished uploading minidump (out-of-process): success = no
assert_20190620190614_11.dmp[14742]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20190620190614_11.dmp[14742]: file ''/tmp/dumps/assert_20190620190614_11.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
sh: 1: /home/squadramunter/.cache/truckersmp-cli/steamcmd/linux32/../ubuntu12_64/gldriverquery: not found
sh: 1: /home/squadramunter/.cache/truckersmp-cli/steamcmd/linux32/../ubuntu12_32/gldriverquery: not found
sh: 1: /home/squadramunter/.cache/truckersmp-cli/steamcmd/linux32/../ubuntu12_64/vulkandriverquery: not found
CAppInfoCacheReadFromDiskThread took 87 milliseconds to initialize`

I add the txt file so you can see it better
[stderr.txt](https://github.com/lhark/truckersmp-cli/files/3311424/stderr.txt)

**Comment by Segelzwerg** [comment] 2019-06-20 19:32
no unfortunately not. 
when I run it with sudo I get the following:
`sudo ./truckersmp-cli -esp -n segelzwerg
fatal: not a git repository (or any of the parent directories): .git
/tmp/truckersmp-cli 100%[===================>]   8,73K  --.-KB/s    in 0,003s  
3502 3456
wine: /home/marcel/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx is not owned by you
Traceback (most recent call last):
  File "/home/marcel/.local/share/truckersmp-cli/Proton/proton", line 428, in <module>
    win_vr_config = subprocess.check_output([wine_path, "winepath", "-w", vr_config], env=env, stderr=lfile).decode("utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/marcel/.local/share/truckersmp-cli/Proton/dist/bin//wine', 'winepath', '-w', '/home/marcel/.steam/steam/config']' returned non-zero exit status 1.`
The error occurs on windows for other games as far as I can tell from searching the internet. The most common solution was to verify the game files, which I did, but did not work or to terminate the firewall, which I do not know to do in a proton environment. Hope this helps.

**Comment by Lucki** [comment] 2019-06-21 13:39
The "application load error" is an error from the steam api not finding the steam client. Since we're in a fake windows environment the steam client is obviously not installed. Steam provides some files for this and proton should take care of that. Maybe something has gone wrong.

Make sure there are files in your prefix at `drive_c/Program Files (x86)/Steam`. Default is `"$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/Steam"`

If they're missing you can copy them over manually from `$XDG_DATA_HOME/Steam/legacycompat`:
~~~
cp -dpr "$XDG_DATA_HOME/Steam/legacycompat/." "$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/Steam"
~~~

The steamVR error is unrelated and shouldn't cause any problems.

@Segelzwerg Never ever run random scripts as root (sudo).

**Comment by squadramunter** [comment] 2019-06-21 13:43
Can you provide a repair parameter for this bash script. You have a solution maybe you can provide a -R or -r parameter to repair this instance? In case other people get the same issue. I tot this error after TruckersMP got a update.

**Comment by Lucki** [comment] 2019-06-21 13:58
I'm quite sure an update for TruckersMP can't cause these issues. The mod is in a completely different folder.

The only thing messing within the prefix is proton, which also got an update some days ago. Did the steps above fix your issue?

**Comment by Segelzwerg** [comment] 2019-06-21 14:09
the only file there is `steamclient64.dll` and there is no `$XDG_DATA_HOME/Steam/legacycompat/`

**Comment by Lucki** [comment] 2019-06-21 14:15
@Segelzwerg Then your problem is probably unrelated. See #32

**Comment by Segelzwerg** [comment] 2019-06-21 14:55
thx for the tipp, for me worked: using #33 but changing:
402: `if [ "$proton" = true ] && ! [ -e "$HOME/.steam/steam/steam.sh" ]; then` to `if [ "$proton" = true ] && ! [ -e "$HOME/.steam/steam.sh" ]; then`
406: `steamdir="$HOME/.steam/steam"` to `steamdir="$HOME/.steam/

**Comment by squadramunter** [comment] 2019-06-21 17:36
> The "application load error" is an error from the steam api not finding the steam client. Since we're in a fake windows environment the steam client is obviously not installed. Steam provides some files for this and proton should take care of that. Maybe something has gone wrong.
> 
> Make sure there are files in your prefix at `drive_c/Program Files (x86)/Steam`. Default is `"$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/Steam"`
> 
> If they're missing you can copy them over manually from `$XDG_DATA_HOME/Steam/legacycompat`:
> 
> ```
> cp -dpr "$XDG_DATA_HOME/Steam/legacycompat/." "$XDG_DATA_HOME/truckersmp-cli/Euro Truck Simulator 2/prefix/pfx/drive_c/Program Files (x86)/Steam/"
> ```
> 
> The steamVR error is unrelated and shouldn't cause any problems.
> 
> @Segelzwerg Never ever run random scripts as root (sudo).

I can confirm that the solution you provided me did work. But why are the files deleted after a update? Has this to do with proton or something? I don't think this is normal. 

Maybe you can provide a solution for people who are counting the same issue? Or when they have auto update on that the files get checked into that folder if they exist otherwise skip copying the files.

**Comment by Lucki** [comment] 2019-06-21 18:18
I'm not sure why they were deleted but even then proton should place them again in the correct folder:

https://github.com/ValveSoftware/Proton/blob/98ef9fc93fe104eae7d7f6ccd54f8e715f54f0f7/proton#L344-L361

So as long I don't know what exactly happened and if it's caused by something we've done this is an issue in proton or user specific which we shouldn't work around.

**Comment by pillowthief** [comment] 2019-06-23 00:23
I had the same issue and the same solution worked for me, very first time using your tool.

**Comment by Lucki** [comment] 2019-06-23 11:04
> […] same issue […] first time using […]

Just tried with a new prefix. The files get copied correctly over, sorry, can't reproduce here.

~~~
ll $XDG_DATA_HOME/truckersmp-cli/Euro\ Truck\ Simulator\ 2/prefix/pfx/drive_c/Program\ Files\ \(x86\)/Steam
insgesamt 1,2M
-rwxr-xr-x 1 lucki lucki 377K 23. Jun 13:01 steamclient64.dll
-rwxr-xr-x 1 lucki lucki 377K 23. Jun 13:01 steamclient.dll
-rwxr-xr-x 1 lucki lucki 377K 23. Jun 13:01 Steam.dll
~~~

**Comment by squadramunter** [comment] 2019-06-23 11:16
My friend also did a fresh installation using this tool and got the same error. Your fix worked but profiles are not visable anymore. Seems like proton connected to steam directly rather then create it's own environment. Strange but when I copy my profiles to the right directory everything is working fine. There must be something going on in this script that does not function anymore.

**Comment by Lucki** [comment] 2019-06-23 11:56
> […] but profiles are not visable anymore. […]

Profiles were always separated. They just recently added cloud sync but I haven't looked into that. It's possible they're not using the same save files for linux and windows or the files have to be uploaded manually. I also doubt that steamcmd picks them up for sync, how should it know where the prefix is?

> […] There must be something going on in this script that does not function anymore.

Well, since there's already a rewrite to python you should also test with that and report back in that pull request.

P.S.: Also please don't mix issues. This is about missing steam fake dlls inside the prefix. Missing save game files (profiles) is a completely different issue.

**Comment by Lucki** [comment] 2020-04-27 23:00
This is probably fixed with the latest update and was caused by setting `STEAM_COMPAT_CLIENT_INSTALL_PATH` to a non-existing path. Since #32 is fixed this should also be fixed now.

https://github.com/lhark/truckersmp-cli/blob/8aa88cafa4933b8fe20df0848b4f27c39edae8fd/truckersmp-cli#L306

Please report back if you're still encountering this error.

**Closed by Lucki** 2020-04-27 23:00 UTC
