### ISSUE TITLE
Can't start truckersmp-cli

### ISSUE THREAD

**Issue by 1s3ct0wN** [lhark/truckersmp-cli#140] opened 2021-01-01 12:13 UTC
Hi everyone, hope you are having excellent day so far!

Im big linux noob and I can't start the launcher to play some ETS2MP this is the exact problem I have.
https://github.com/lhark/truckersmp-cli/issues/120

Unfortunately I'm not smart enough to realize how to solve it am using Ubuntu 20.10 with AMD RX580 and open source drivers..
Thank you!

**Comment by kakurasan** [comment] 2021-01-01 14:23
See [our installation instruction](https://github.com/lhark/truckersmp-cli#install) first. If users try to start in our Git directory it won't start because the required file `truckersmp_cli/truckersmp-cli.exe` is missing (It was removed when [version 0.1.0 was released](https://github.com/lhark/truckersmp-cli/commit/93c7960d7242f0010cee09e7eee57a2ad458365b)).

The recommended way is to install via PyPI.

```
$ python3 -m pip install --user truckersmp-cli[optional]
```

Then see [examples](https://github.com/lhark/truckersmp-cli#usage-examples).

**Comment by 1s3ct0wN** [comment] 2021-01-01 14:27
https://pastebin.com/WBakcP3V

![Screenshot from 2021-01-01 08-24-04](https://user-images.githubusercontent.com/76838973/103440442-2a1fa400-4c0b-11eb-843f-06440bdcb7aa.png)

**Comment by Lucki** [comment] 2021-01-01 14:40
I can't see any error in your screenshot. Make sure you've closed all related processes and:

Unfortunately you ignored our precious issue template when creating this issue so I have to ask for additional information. Please fill out the issue template. You can find the latest issue template here: https://raw.githubusercontent.com/lhark/truckersmp-cli/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by 1s3ct0wN** [comment] 2021-01-01 15:19
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
---

[comment]: # (Run your command with additional informational output [-v] and try to pinpoint the problem first.)

## Describe the bug
When starting ./truckersmp-cli and after it downloaded the game and tried to start it is giving me this error in the CMD which opens: Pipe Server: Main thread awaiting client connection on \\.\pipe\discord-ipc-0.

When trying the --without-wine-discord-ipc-bridge command it won't even open a cmd it just crashes after a few seconds.

## Expected behavior
To start the game with multiplayer

## Command
~~~
Replace this line with the command you've run [e.g. dak0@dak0:~/Downloads/truckersmp-cli-master$ ./truckersmp-cli --without-wine-discord-ipc-bridge -vv

~~~

## Terminal output
<details><summary>~/Downloads/truckersmp-cli-master$ ./truckersmp-cli --without-wine-discord-ipc-bridge -vv
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/dak0/.local/share/truckersmp-cli/TruckersMP
** INFO **  --update/--start not specified, doing both.
** INFO **  --ats/--ets2 not specified, choosing ETS2.
** INFO **  Platform is Linux, using Proton
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/dak0/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
** INFO **  Prefix: /home/dak0/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
** INFO **  Proton directory: /home/dak0/.local/share/truckersmp-cli/Proton
** DEBUG **  Updating game files
** INFO **  SteamCMD: /home/dak0/.local/share/truckersmp-cli/steamcmd/steamcmd.sh
** DEBUG **  Closing Linux version of Steam
Running Steam on ubuntu 20.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
/home/dak0/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad -shutdown
** DEBUG **  Updating Proton (AppID:1420170)
** INFO **  Command:
  /home/dak0/.local/share/truckersmp-cli/steamcmd/steamcmd.sh
    +login 1s3ct0wn
    +force_install_dir /home/dak0/.local/share/truckersmp-cli/Proton
    +app_update 1420170 validate
    +quit
Redirecting stderr to '/home/dak0/.steam/debian-installation/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...CreateBoundSocket: ::bind couldn't find an open port between 27060 and 27060
OK.
Logging in user '1s3ct0wn' to Steam Public ...
Logged in OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.02 (167846 / 908549477)
Success! App '1420170' fully installed.
** INFO **  Game branch: public
** DEBUG **  Updating Game (AppID:227300)
** INFO **  Command:
  /home/dak0/.local/share/truckersmp-cli/steamcmd/steamcmd.sh
    +@sSteamCmdForcePlatformType windows
    +login 1s3ct0wn
    +force_install_dir /home/dak0/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
    +app_update 227300 -beta public validate
    +quit
Redirecting stderr to '/home/dak0/.steam/debian-installation/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@sSteamCmdForcePlatformType" = "windows"
Logging in user '1s3ct0wn' to Steam Public ...
Logged in OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.00 (0 / 4879899231)
 Update state (0x5) verifying install, progress: 16.48 (804017057 / 4879899231)
 Update state (0x5) verifying install, progress: 36.20 (1766378987 / 4879899231)
 Update state (0x5) verifying install, progress: 56.23 (2744114951 / 4879899231)
 Update state (0x5) verifying install, progress: 76.04 (3710729007 / 4879899231)
 Update state (0x5) verifying install, progress: 96.12 (4690325679 / 4879899231)
Success! App '227300' fully installed.
** DEBUG **  Updating mod files
** DEBUG **  No files to download
** DEBUG **  Starting game with Proton
** DEBUG **  Starting Steam...
                                                                      
** DEBUG **  Steam should now be up and running and the user logged in.
** INFO **  Steam installation directory: /home/dak0/.steam/debian-installation
** INFO **  Startup command:
  SteamGameId=227300
  SteamAppId=227300
  STEAM_COMPAT_DATA_PATH=/home/dak0/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/dak0/.steam/debian-installation
  PROTON_USE_WINED3D=0
  PROTON_NO_D3D11=1
  LD_PRELOAD=/home/dak0/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so
  /usr/bin/python3 /home/dak0/.local/share/truckersmp-cli/Proton/proton
  run
  /home/dak0/Downloads/truckersmp-cli-master/truckersmp_cli/truckersmp-cli.exe /home/dak0/.local/share/truckersmp-cli/Euro Truck Simulator 2/data /home/dak0/.local/share/truckersmp-cli/TruckersMP
** INFO **  Proton output:
ERROR: ld.so: object '/home/dak0/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/dak0/.steam/debian-installation/ub</summary>

~~~
Replace this line with the terminal output you're getting
when running the command with debug output [-vv]
~~~
</details>

## Screenshots
![Screenshot from 2021-01-01 08-24-04](https://user-images.githubusercontent.com/76838973/103441192-d9f81000-4c11-11eb-9529-09b474738204.png)


[comment]: # (If applicable, add screenshots to help explain your problem:)

</details>

## Information
 - OS: 20.10
 - Proton or Wine version: Proton 5.13-4 
 - truckersmp-cli version: 0.3.0

## Additional context
python3 -m pip install truckersmp-cli

python3 -m pip install truckersmp-cli[optional]

python3 -m pip install truckersmp-cli --upgrade

All run
-----------------------------------------------------------------
sudo apt install libsdl2-dev libsdl2-2.0-0
Reading package lists... Done
Building dependency tree
Reading state information... Done
libsdl2-2.0-0 is already the newest version (2.0.12+dfsg1-4).
libsdl2-dev is already the newest version (2.0.12+dfsg1-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
---------------------------------------------------------------------
python3 --version
Python 3.8.6

**Comment by Lucki** [comment] 2021-01-01 15:37
Please correctly format your message next time.

> `dak0@dak0:~/Downloads/truckersmp-cli-master$ ./truckersmp-cli […]`

You're not using the recommended installed version. You're still using your downloaded copy of the repository which…

> [[…] the required file `truckersmp_cli/truckersmp-cli.exe` is missing […]](https://github.com/lhark/truckersmp-cli/issues/140#issuecomment-753322898)

**Comment by 1s3ct0wN** [comment] 2021-01-01 17:04
Would you be so kind to help me do that please?

**Comment by Lucki** [comment] 2021-01-01 17:18
If the python installation path is in your `$PATH` you can run directly `truckersmp-cli` (no `./`).

If it's not you have to locate the installation path (I assume somewhere in `~/.local/bin?`) and either start it from there locally (`./truckersmp-cli`) or add the path to your `$PATH`.

**Comment by 1s3ct0wN** [comment] 2021-01-01 17:29
It works now thank you very much!

**Comment by Lucki** [comment] 2021-01-01 17:48
Duplicate of #92

**Closed by Lucki** 2021-01-01 17:48 UTC

**Comment by kakurasan** [comment] 2021-01-02 04:54
@1s3ct0wN Congrats and have fun.

@Lucki The "It doesn't start because of missing truckersmp-cli.exe" issue was reported 4 times (issue 88, 92, 120, and this).
We might have to add "FAQ" section to README for this. But at the same time, it's better to also check whether `truckersmp_cli/truckersmp-cli.exe` is present. Currently it doesn't print error messages when the file is missing. This is confusing for users and is a problem.
