### ISSUE TITLE
Game Crash: Index outside array boundaries

### ISSUE THREAD

**Issue by Rapp3rX** [lhark/truckersmp-cli#60] opened 2020-05-02 20:37 UTC
Hi! I've tried to install TruckersMP with that cli, and I ended right there:
https://pastebin.com/9CsHDat8

I'm using this script:
https://pastebin.com/844Qt2At

It doesn't matter if I'm using OpenGL, I get the same error every time, and my game crash.

**Comment by Lucki** [comment] 2020-05-02 23:48
Looks like #36 is still happening. For previous reports "waiting and updating" was the solution.

Which kernel version are you running?
Please also try with Proton 5.0

**Comment by Rapp3rX** [comment] 2020-05-03 08:45
I started with Proton 5.0, that's why I switched back to 4.11.

I have 5.3.0-51-generic kernel version.

**Comment by Lucki** [comment] 2020-05-03 13:24
Hm, we have reports that it started working with 5.3. Also after switching to Manjaro where 5.4 was the most recent one.
Please try an update if possible, latest LTS version is 5.4.38 and latest stable is 5.6.10 according to [kernel.org](https://www.kernel.org/).

Is there _something_ you can imagine that is somewhat unusual and related to your input devices? An array index outside boundaries error generally rise up when it tries to access more items in a list then there are available.
Do you subscribed to any mods in the workshop or manually tried to use mods related to input devices?
You're using the prefix from your steam installation. Please also try with a clean one and no savegame in it.

**Comment by Rapp3rX** [comment] 2020-05-03 14:49
I've updated my kernel to 5.4.28 and still getting the issue.
I deleted the workshop mods, still getting the issue.
This is a pure installation. Taking out my profile give me the same.
I'm using the native Steam without modifications.

**Comment by Lucki** [comment] 2020-05-04 13:25
I'm sorry I can't help more. We don't know what's causing this issue but we're almost sure it's not caused by this script. The mod already loaded successfully so the script is done with it's part.
If you get to know what is causing this issue then **please report back**.

But for now it's a duplicate of #36

**Comment by Lucki** [comment] 2020-05-04 13:26
Duplicate of #36

**Comment by Rapp3rX** [comment] 2020-05-04 17:51
Well, it's my fault. I'm gonna try a different distro when I'll have time for it. I'll notify you when I can solve.

Thank you for making this CLI, I really like it!

**Comment by Lucki** [comment] 2020-05-04 18:45
> Well, it's my fault.

Probably not. It's just an unlucky combination of _something_ we're not aware of (yet).

**Comment by squadramunter** [comment] 2020-05-05 22:27
I think I found the root cause of the problem why it is giving that error. I reproduced that error by a clean install without installed winehq-stable package. Since I am installing the winehq-stable package it runs fine using that proton option. So I think Proton needs some Wine libs to work propery. I tested this on Fedora 32 and it works fine now.

So it's required to have a working wine version on your system. Recommended packages

Installed:
  SDL2-2.0.12-1.fc32.i686                                                    
  SDL2-2.0.12-1.fc32.x86_64                                                  
  cdparanoia-libs-10.2-31.fc32.i686                                          
  gd-2.3.0-1.fc32.i686                                                       
  graphene-1.10.0-2.fc32.i686                                                
  gstreamer1-1.16.2-2.fc32.i686                                              
  gstreamer1-plugins-base-1.16.2-3.fc32.i686                                 
  libFAudio-20.04-1.fc32.i686                                                
  libFAudio-20.04-1.fc32.x86_64                                              
  libXpm-3.5.13-2.fc32.i686                                                  
  libXv-1.0.11-11.fc32.i686                                                  
  libattr-2.4.48-8.fc32.i686                                                 
  libexif-0.6.21-21.fc32.i686                                                
  libglvnd-egl-1:1.3.1-1.fc32.i686                                           
  libglvnd-gles-1:1.3.1-1.fc32.i686                                          
  libgomp-10.0.1-0.13.fc32.i686                                              
  libgphoto2-2.5.23-2.fc32.i686                                              
  libieee1284-0.2.11-32.fc32.i686                                            
  libieee1284-0.2.11-32.fc32.x86_64                                          
  libimagequant-2.12.6-2.fc32.i686                                           
  libpcap-14:1.9.1-3.fc32.i686                                               
  libraqm-0.7.0-5.fc32.i686                                                  
  libtheora-1:1.1.1-25.fc32.i686                                             
  libtool-ltdl-2.4.6-33.fc32.i686                                            
  libv4l-1.18.0-4.fc32.i686                                                  
  libvisual-1:0.4.0-28.fc32.i686                                             
  libvkd3d-1.1-4.fc32.i686                                                   
  libvkd3d-1.1-4.fc32.x86_64                                                 
  libwayland-server-1.18.0-1.fc32.i686                                       
  libwebp-1.1.0-2.fc32.i686                                                  
  libxslt-1.1.34-1.fc32.i686                                                 
  lockdev-1.0.4-0.33.20111007git.fc32.i686                                   
  mesa-libEGL-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686                       
  mesa-libOSMesa-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686                    
  mesa-libOSMesa-20.1.0-0.3.20200501.00.1d0bd55.fc32.x86_64                  
  mesa-libgbm-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686                       
  mpg123-libs-1.25.12-2.fc32.i686                                            
  ocl-icd-2.2.12-9.fc32.i686                                                 
  openal-soft-1.19.1-5.fc32.i686                                             
  opus-1.3.1-3.fc32.i686                                                     
  orc-0.4.31-2.fc32.i686                                                     
  readline-8.0-4.fc32.i686                                                   
  sane-backends-1.0.29-7.fc32.x86_64                                         
  sane-backends-drivers-cameras-1.0.29-7.fc32.i686                           
  sane-backends-drivers-cameras-1.0.29-7.fc32.x86_64                         
  sane-backends-drivers-scanners-1.0.29-7.fc32.i686                          
  sane-backends-drivers-scanners-1.0.29-7.fc32.x86_64                        
  sane-backends-libs-1.0.29-7.fc32.i686                                      
  spirv-tools-libs-2019.5-2.20200421.git67f4838.fc32.i686                    
  unixODBC-2.3.7-6.fc32.i686                                                 
  unixODBC-2.3.7-6.fc32.x86_64                                               
  wine-stable-common-1:5.0.0-8.1.i686                                        
  wine-stable64-1:5.0.0-8.1.x86_64                                           
  winehq-stable-1:5.0.0-8.1.x86_64                                           

Complete!
[squadramunter@localhost truckersmp-cli]$ wine --version
wine-5.0

I can't say what package solve the problem but for me winehq-stable did the trick!

@Rapp3rX Can you comfirm that after installing winehq-stable everyting works fine?

**Comment by squadramunter** [comment] 2020-05-05 22:29
> I think I found the root cause of the problem why it is giving that error. I reproduced that error by a clean install without installed winehq-stable package. Since I am installing the winehq-stable package it runs fine using that proton option. So I think Proton needs some Wine libs to work properly. I tested this on Fedora 32 and it works fine now.
> 
> So it's required to have a working wine version on your system. Recommended packages
> 
> Installed:
> SDL2-2.0.12-1.fc32.i686
> SDL2-2.0.12-1.fc32.x86_64
> cdparanoia-libs-10.2-31.fc32.i686
> gd-2.3.0-1.fc32.i686
> graphene-1.10.0-2.fc32.i686
> gstreamer1-1.16.2-2.fc32.i686
> gstreamer1-plugins-base-1.16.2-3.fc32.i686
> libFAudio-20.04-1.fc32.i686
> libFAudio-20.04-1.fc32.x86_64
> libXpm-3.5.13-2.fc32.i686
> libXv-1.0.11-11.fc32.i686
> libattr-2.4.48-8.fc32.i686
> libexif-0.6.21-21.fc32.i686
> libglvnd-egl-1:1.3.1-1.fc32.i686
> libglvnd-gles-1:1.3.1-1.fc32.i686
> libgomp-10.0.1-0.13.fc32.i686
> libgphoto2-2.5.23-2.fc32.i686
> libieee1284-0.2.11-32.fc32.i686
> libieee1284-0.2.11-32.fc32.x86_64
> libimagequant-2.12.6-2.fc32.i686
> libpcap-14:1.9.1-3.fc32.i686
> libraqm-0.7.0-5.fc32.i686
> libtheora-1:1.1.1-25.fc32.i686
> libtool-ltdl-2.4.6-33.fc32.i686
> libv4l-1.18.0-4.fc32.i686
> libvisual-1:0.4.0-28.fc32.i686
> libvkd3d-1.1-4.fc32.i686
> libvkd3d-1.1-4.fc32.x86_64
> libwayland-server-1.18.0-1.fc32.i686
> libwebp-1.1.0-2.fc32.i686
> libxslt-1.1.34-1.fc32.i686
> lockdev-1.0.4-0.33.20111007git.fc32.i686
> mesa-libEGL-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686
> mesa-libOSMesa-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686
> mesa-libOSMesa-20.1.0-0.3.20200501.00.1d0bd55.fc32.x86_64
> mesa-libgbm-20.1.0-0.3.20200501.00.1d0bd55.fc32.i686
> mpg123-libs-1.25.12-2.fc32.i686
> ocl-icd-2.2.12-9.fc32.i686
> openal-soft-1.19.1-5.fc32.i686
> opus-1.3.1-3.fc32.i686
> orc-0.4.31-2.fc32.i686
> readline-8.0-4.fc32.i686
> sane-backends-1.0.29-7.fc32.x86_64
> sane-backends-drivers-cameras-1.0.29-7.fc32.i686
> sane-backends-drivers-cameras-1.0.29-7.fc32.x86_64
> sane-backends-drivers-scanners-1.0.29-7.fc32.i686
> sane-backends-drivers-scanners-1.0.29-7.fc32.x86_64
> sane-backends-libs-1.0.29-7.fc32.i686
> spirv-tools-libs-2019.5-2.20200421.git67f4838.fc32.i686
> unixODBC-2.3.7-6.fc32.i686
> unixODBC-2.3.7-6.fc32.x86_64
> wine-stable-common-1:5.0.0-8.1.i686
> wine-stable64-1:5.0.0-8.1.x86_64
> winehq-stable-1:5.0.0-8.1.x86_64
> 
> Complete!
> [squadramunter@localhost truckersmp-cli]$ wine --version
> wine-5.0
> 
> I can't say what package solve the problem but for me winehq-stable did the trick!
> 
> @Rapp3rX Can you comfirm that after installing winehq-stable everyting works fine?

I also recommend this on your system to get better performance.
https://github.com/FeralInteractive/gamemode

**Comment by kakurasan** [comment] 2020-05-06 03:39
It seems (64-bit version of) libSDL2 needs to be installed. I can reproduce this on my Ubuntu 20.04:

1. Install libSDL2
2. Move or rename `/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0`
3. Try to start Multiplayer game: Crashing (Index outside array boundaries.)
4. Restore `libSDL2-2.0.so.0`
5. Try to start Multiplayer game: Working as expected

Thank you @squadramunter for providing the useful information.

**Comment by squadramunter** [comment] 2020-05-06 06:19
@kakurasan great that you were able to find the root cause of the problem. libsdl2 on Debian/Ubuntu or sdl2 on Arch/Fedora seems to be for your inputs. Keyboard, Mouse, Controller etc.

**Comment by squadramunter** [comment] 2020-05-06 09:43
I can comfirm that the missing package libsdl2 is the root cause of the problem.

These libs are now on my system and when I rename them I got that error again.

Running Fedora 32

/usr/lib/libSDL2-2.0.so.0
/usr/lib/libSDL2-2.0.so.0.12.0
/usr/lib64/libSDL2-2.0.so.0
/usr/lib64/libSDL2-2.0.so.0.12.0

Thanks @kakurasan for your help in this issue. Now let's focus on how to get this issue patched in the next update. :+1:

**Closed** 2020-05-09 13:12 UTC
