### ISSUE TITLE
After a recent ETS2MP Launcher update, the cli version fails.

### ISSUE THREAD

**Issue by Sweeper5** [lhark/truckersmp-cli#4] opened 2017-05-15 22:13 UTC
After this new fancy ETS2 MP update, using this launcher, it seems to malform the update somehow.
I am getting an error about ETS2 being out of date, requesting version: 1.27.2.1.s
However it says the game version that is installed is: 1.27.1.7
But launching the installed game without MP reports the correct version of 1.27.2.1.s that the MP launcher requests.

I am not sure if this is a problem with ETS 2 MP, referencing this post: https://forum.truckersmp.com/index.php?/topic/47843-launcher-does-not-work/
Or if there is an issue with version handling for the CLI launcher, however I am posting it regardless to draw attention to it.

Thanks for making a good launcher in any case.

**Comment by lhark** [comment] 2017-05-16 00:57
I'm afraid I cannot reproduce the problem, everything is working correctly on my end :/

However, in the forum post you mentionned, they point to this potential solution : https://forum.truckersmp.com/index.php?/topic/47822-unsupported-game-version-detected-if-game-meets-the-requirements/

Anyway, most of the time, those problems have to do with the game install itself, my launcher only downloads the latest mod files and performs the DLL injection to launch the mod.

Do you have another launcher working to confirm or infirm the problem ?

**Comment by lhark** [comment] 2017-09-24 21:41
Four months without any answer: closing.

**Closed by lhark** 2017-09-24 21:41 UTC
