### ISSUE TITLE
[p3api] Index outside array boundaries.

### ISSUE THREAD

**Issue by squadramunter** [lhark/truckersmp-cli#36] opened 2019-06-28 20:23 UTC
Hello I got a strange error going on here on my ubuntu mate desktop

[00:29:38] [error] Failed to load texture '/ui/refresh.png'.

[22:21:13] [error] [p3api] c:\gitlab-runner\builds\yzxsqr8y\0\game\truckersmp\src\multiplayer\client\prismapi\p3containers\src\array.inl(44): ?get_at@?$array_t@V?$auto_ptr_t@Vinput_device_t@prism@@@prism@@@prism@@QEBAAEAV?$auto_ptr_t@Vinput_device_t@prism@@@2@_K@Z: Index outside array boundaries.

Hope someone can help me solve this problem.

**Comment by squadramunter** [comment] 2019-06-28 21:24
The game opens as a black window and then a error message pops up. I don't know if this happens to others on Ubuntu Mate?

**Comment by squadramunter** [comment] 2019-06-29 10:58
@lhark @Lucki @kakurasan Are you guys know what's happening? It did work before but now it gives this error. Please come with a solution ASAP.

**Comment by Matze1224** [comment] 2019-08-06 18:45
Same error, can't start game. Only a generic failure window "Game crashed - FATAL ERROR" with the message: "An application fatal error! Do you want to send crash.log file to developers?".

Error looks the same:
```
[20:35:06] <info> [p3api] Game version is supported. Base address: 0000000000000000 Signature: e3d44f3298ee
[20:35:06] <info> [net] [http async] Creating thread(s)[1]...
[20:35:06] <info> [net] [http async] Thread(s) created.
[20:35:06] <info> [client] Initialized successfully.
Setting breakpad minidump AppID = 270880
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198112769893 [API loaded no]
[20:35:09] <info> [gl] Display init.
[20:35:09] <info> [gl] OpenGL version: 3.3.0 NVIDIA 418.74 [3.3] Using: core
[20:35:09] <info> [inp] Keyboard input initialized. Input resolution = 1920x1080.
[20:35:10] <error> Failed to load texture '/ui/refresh.png'.
[20:35:10] <info> [gl] Device initialized.
[20:35:10] <error> [p3api] c:\gitlab-runner\builds\yzxsqr8y\1\game\truckersmp\src\multiplayer\client\prismapi\p3containers\src\array.inl(44): ?get_at@?$array_t@V?$auto_ptr_t@Vinput_device_t@prism@@@prism@@@prism@@QEBAAEAV?$auto_ptr_t@Vinput_device_t@prism@@@2@_K@Z: Index outside array boundaries.
```

This is the crash log:
```
-----------------------------------------------
Crash log 22.07.2019, 19:14:31
Game name: American Truck Simulator Multiplayer, version: 0.2.2.6.1, renderer: dx9
OS: Windows 7, NT: 6.1
CPU[1/4]: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
CPU[2/4]: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
CPU[3/4]: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
CPU[4/4]: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz

AvailMEM Virt:134217727MB Phys:14136MB Total:134231863MB
TotalMEM Virt:134217727MB Phys:16018MB Total:134233745MB

Exe base address: 0000000140000000
Exception address: 00007FDE486741E7
Exception code: C0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception flags: 0
Module file name: Z:\usr\steam\steamapps\common\American Truck Simulator\bin\win_x64\amtrucks.exe
Address without base: 00007FDE486741E7

RAX: 6E65766500657375
RCX: 0000000000000200
RDX: 0000000000000000
RBX: 0000000000000135
RBP: 0000000000000000
RSI: 0000000000000135
RDI: 000000007E795100
R8:  0000000000000000
R9:  0000000000000000
R10: 0000000000000008
R11: 0000000000000246
R12: 000000000194CD90
R13: 0000000000000135
R14: 000000000194C3C0
R15: 00000000000007B9
CS:RIP: 0033:00007FDE486741E7
SS:RSP: 002B:000000000022F840
DS: 0000 
ES: 0000 
FS: 0000 
GS: 0000 
EFlags: 10216 
XMM0: 0000000000000000:0000000000000000 
XMM1: 0000000000000000:0000000000000000 
XMM2: FFFFFFFFFFFFFFFF:FF00FF00FF00FF00 
XMM3: 0000000000000000:0000000000000000 
XMM4: 0000000000000000:0000000000000000 
XMM5: 5A5A5A5A5A5A5A5A:5A5A5A5A5A5A5A5A 
XMM6: 0000000000000000:0000000000000000 
XMM7: 0000000000000000:0000000000000000 
XMM8: 000011780000AC80:0000AB4800000108 
XMM9: 0000000000000000:0000000000000000 
XMM10: 0000000000000000:0000000000000000 
XMM11: 0000000000000000:0000000000000000 
XMM12: 0000000000000000:0000000000000000 
XMM13: 0000000000000000:0000000000000000 
XMM14: 0000000000000000:0000000000000000 
XMM15: 0000000000000000:0000000000000000 


EIP bytecode:
  74 37 8B 47 50 39 F0 7E 10 48 8B 47 58 48 63 F6
> 0F B6 04 30 48 83 C4 08 C3 89 C6 48 8D 3D 2E 5A
  0B 00 31 C0 E8 D0 00 FE FF 31 C0 48 83 C4 08 C3


Call stack:
         Address             Frame              Base                Module  Additional


Stack:
  90 CD 94 01 00 00 00 00 FF FF FF FF 00 00 00 00 6E C0 01 00 00 00 00 00 00 00 00 00 00 00 00 00
  B9 07 00 00 00 00 00 00 AE 3E 7B 48 DE 7F 00 00 20 F8 22 00 00 00 00 00 C9 94 45 7B 00 00 00 00
  00 00 00 00 00 00 00 00 50 F9 22 00 00 00 00 00 90 CD 94 01 00 00 00 00 34 01 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 90 CD 94 01 00 00 00 00 34 01 00 00 00 00 00 00 C0 C3 94 01 00 00 00 00
> B9 07 00 00 00 00 00 00 2D 0A 7D 48 DE 7F 00 00 80 06 94 01 00 00 00 00 98 CD 94 01 00 00 00 00
  50 F9 22 00 00 00 00 00 1C 00 00 00 00 00 00 00 18 00 00 00 00 00 00 00 C0 C3 94 01 00 00 00 00
  38 D4 39 41 01 00 00 00 0A 7A 7C 48 DE 7F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 01 00 00 48 AB 00 00
  80 AC 00 00 78 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 C0 C3 94 01 00 00 00 00
  04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 FA 22 00 00 00 00 00 DD 6F 1F 40 01 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  D0 E2 D8 00 00 00 00 00 D9 9D 1F 40 01 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 08 01 00 00 48 AB 00 00 80 AC 00 00 78 11 00 00
  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  38 D4 39 41 01 00 00 00 DA CC 1D 40 01 00 00 00 00 00 00 00 00 00 00 00 D0 E2 D8 00 00 00 00 00
  04 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 D0 1D 40 01 00 00 00

Modules:
0000000140000000 0167D000 0000000141651310 Z:\usr\steam\steamapps\common\American Truck Simulator\bin\win_x64\amtrucks.exe
000000007BC20000 00122000 000000007BCC3A70 C:\windows\system32\ntdll.dll
000000007B420000 00405000 000000007B4A2AF0 C:\windows\system32\KERNEL32.dll
000000003B400000 00041000 000000003B40B7A8 Z:\usr\steam\steamapps\common\American Truck Simulator\bin\win_x64\steam_api64.dll
00007FDE850E0000 00079000 00007FDE8512E170 C:\windows\system32\advapi32.dll
00007FDE845E0000 009E8000 00007FDE84689610 C:\windows\system32\shell32.dll
00007FDE84550000 0006C000 00007FDE84588BA0 C:\windows\system32\shlwapi.dll
00007FDE842F0000 00244000 00007FDE843A80A0 C:\windows\system32\user32.dll
00007FDE84170000 00160000 00007FDE84207560 C:\windows\system32\gdi32.dll
00007FDE85B70000 0000B000 00007FDE85B76820 C:\windows\system32\version.dll
00007FDE84130000 00020000 00007FDE84145320 C:\windows\system32\shcore.dll
00007FDE7FE80000 00180000 00007FDE7FF70AA0 C:\windows\system32\ole32.dll
00007FDE840A0000 00087000 00007FDE840F1170 C:\windows\system32\rpcrt4.dll
00007FDE7FD10000 0014B000 00007FDE7FDCBAB0 C:\windows\system32\oleaut32.dll
00007FDE84050000 00038000 00007FDE84078280 C:\windows\system32\ws2_32.dll
00007FDE7FBF0000 000F7000 00007FDE7FC260A0 C:\windows\system32\comdlg32.dll
00007FDE7FA90000 00152000 00007FDE7FB51880 C:\windows\system32\comctl32.dll
00007FDE7FA40000 00049000 00007FDE7FA6F150 C:\windows\system32\usp10.dll
00007FDE84030000 00019000 00007FDE8403E6B0 C:\windows\system32\imm32.dll
00007FDE7FA00000 0003B000 00007FDE7FA22C60 C:\windows\system32\winspool.drv
00007FDE84010000 0000F000 00007FDE8401C9D0 C:\windows\system32\msimg32.dll
00007FDE7F980000 00071000 00007FDE7F9BD4A0 C:\windows\system32\setupapi.dll
00007FDE7F8C0000 000B3000 00007FDE7F8E58C0 C:\windows\system32\winmm.dll
00007FDE7F890000 0001D000 00007FDE7F89EC80 C:\windows\system32\msacm32.dll
00007FDE7F390000 00095000 00007FDE7F3E5F70 C:\windows\system32\winex11.drv
00007FDE7E140000 0003B000 00007FDE7E161840 C:\windows\system32\uxtheme.dll
0000000180000000 00E07000 0000000180E02AA0 Z:\home\matze\.local\share\truckersmp-cli\TruckersMP\core_atsmp.dll
00007FDE7D400000 000E3000 00007FDE7D470E20 C:\windows\system32\crypt32.dll
00007FDE7D3E0000 00015000 00007FDE7D3ECAF0 C:\windows\system32\bcrypt.dll
00007FDE7D370000 0005F000 00007FDE7D3A83F0 C:\windows\system32\wldap32.dll
00007FDE7E130000 0000D000 00007FDE7E139D50 C:\windows\system32\api-ms-win-core-synch-l1-2-0.dll
00007FDE7D2D0000 00013000 00007FDE7D2E0810 C:\windows\system32\api-ms-win-core-fibers-l1-1-1.dll
00007FDE7D2C0000 0000F000 00007FDE7D2CBDF0 C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
00007FDE7D2B0000 0000A000 00007FDE7D2B6B70 C:\windows\system32\api-ms-win-core-sysinfo-l1-2-1.dll
00007FDE7D270000 00035000 00007FDE7D293810 C:\windows\system32\secur32.dll
00007FDE7D230000 00033000 00007FDE7D2527A0 C:\windows\system32\netapi32.dll
00007FDE7D200000 0002C000 00007FDE7D21F090 C:\windows\system32\iphlpapi.dll
00007FDE7D1F0000 0000B000 00007FDE7D1F6C30 C:\windows\system32\kerberos.dll
00007FDE7D1D0000 00010000 00007FDE7D1DD8D0 C:\windows\system32\api-ms-win-core-file-l2-1-1.dll
00007FDE7D110000 000BC000 00007FDE7D18D280 C:\windows\system32\msvcrt.dll
00007FDE7CEC0000 00233000 00007FDE7CFF0AA0 C:\windows\system32\lsteamclient.dll
00007FDE7B1B0000 00004000 00007FDE7B1B1850 C:\windows\system32\api-ms-win-core-string-l1-1-0.dll
00007FDE7B190000 00010000 00007FDE7B19CC50 C:\windows\system32\api-ms-win-appmodel-runtime-l1-1-1.dll
00007FDE487A0000 0005D000 00007FDE487D7B60 C:\windows\system32\dinput8.dll
00007FDE48790000 00009000 00007FDE48794230 C:\windows\system32\xinput1_4.dll
00007FDE48040000 0000B000 00007FDE48046D50 C:\windows\system32\hid.dll
00007FDE43520000 00036000 00007FDE435408E0 C:\windows\system32\winhttp.dll
00007FDE48020000 00011000 00007FDE48025600 C:\windows\system32\jsproxy.dll
00007FDE434E0000 00032000 00007FDE434F8460 C:\windows\system32\rsaenh.dll
00007FDE43480000 00050000 00007FDE434B34E0 C:\windows\system32\d3d9.dll
00007FDE43320000 0015C000 00007FDE433FB140 C:\windows\system32\wined3d.dll
000000007A850000 001B9000 000000007A937900 C:\windows\system32\opengl32.dll
000000006F200000 00192000 000000006F201330 C:\windows\system32\DXGI.dll
00007FDE40D80000 0000A000 00007FDE40D83B50 C:\windows\system32\vulkan-1.dll
00007FDE3AD70000 0003C000 00007FDE3AD939E0 C:\windows\system32\winevulkan.dll
000000001E310000 00094000 000000001E325AB4 C:\windows\system32\openvr_api_dxvk.dll
00007FDE3AD50000 0000B000 00007FDE3AD587E0 C:\windows\system32\api-ms-win-security-systemfunctions-l1-1-0.dll
000000002F830000 00075000 000000002F868DB8 Z:\usr\steam\steamapps\common\American Truck Simulator\bin\win_x64\swopenal32.dll
00007FDE3AAA0000 0001A000 00007FDE3AAAE0E0 C:\windows\system32\mmdevapi.dll
00007FDE3AA70000 00023000 00007FDE3AA854B0 C:\windows\system32\winepulse.drv
00007FDE38FA0000 0004C000 00007FDE38FC8D90 C:\windows\system32\dsound.dll
00000000300C0000 00468000 00000000301BA078 Z:\usr\steam\steamapps\common\American Truck Simulator\bin\win_x64\tobii_gameintegration_x64.dll
00007FDE391B0000 00013000 00007FDE391BE5B0 C:\windows\system32\schannel.dll
00007FDE39030000 00060000 00007FDE3906E740 C:\windows\system32\dbghelp.dll
00007FDE390A0000 0000C000 00007FDE390A9A00 C:\windows\system32\psapi.dll
```

System is a Debian testing with Mate, using a bumblebee setup (but I don't think this is the point cause it worked before).

**Comment by Matze1224** [comment] 2019-08-11 11:48
The error looks like from the TruckersMP mod, cause no changes happened from this launcher. The game launches on windows without any problem. I don't think we get different result with using wine instead of proton - but nothing tested.
Does anyone know what ``prismapi`` or ``p3api`` is? I searched the source from the TruckersMP mod but didn't found anything. Guess this is a strange error happening only with wine (cause windows works).

But in a default log, it outputs a message to initialize the mouse, and the error message sounds like it happened on an array with input devices. Does they changed something for calling the mouse and know wine do something differently than the windows api?

**Comment by kakurasan** [comment] 2019-08-15 14:10
> I don't think we get different result with using wine instead of proton - but nothing tested.

I tested ETS2MP and ATSMP with Wine (4.0.1 and 4.13): Both work for me.

"ETS2MP + Proton" and "ATSMP + Proton", too, work for me: The same result.

* ETS2 1.35.1.31s
* ATS 1.35.1.31s

> Does anyone know what prismapi or p3api is?

I *guess* they mean an API for [Prism3D Game Engine](https://scssoft.com/technology) and it's used in TruckersMP MOD (`core_*mp.dll`). I found lots of `prism` stuff in `core_*mp.dll` (Use `upx -d` and `strings` + `grep`).

**Comment by Lucki** [comment] 2019-08-17 23:17
I don't think this is caused by the general setup as it works for new and also existing setups. There can however be a problem with you specific setup which maybe was introduced by a bug or something else.

Has it ever worked for you before? I guess this one's a yes so maybe try with all mod files deleted, with a new prefix (backup your save file) and as really last step with redownloaded gamefiles. Also try combinations of these.

**Comment by Matze1224** [comment] 2019-08-18 07:16
Good for you, but for me, it does not work yet. I tried it on an other installation on my pc, but does not work either. But thanks for the information that there is hope outside ;-) !

**Comment by Matze1224** [comment] 2019-12-17 16:48
For me, it works again, but currently don't use it, cause have problems with the new 5.3 linux kernel and my steering wheel.

For me, this can be closed, but I don't know the state of @squadramunter ..

**Comment by Joggingbrot551** [comment] 2019-12-25 22:00
Hello,
I installed the newest version of python port with the --singleplayer option. 
With the --singleplayer option the game launches successfully but the multiplayer causes the same error:
![Index outside array boundarie](https://user-images.githubusercontent.com/59224920/71450866-5b4cd500-276a-11ea-8de2-df0d3d975a2a.png)

@Matze1224 how did you fix it?
Best regards

**Comment by Matze1224** [comment] 2019-12-30 09:57
My fix was to wait (currently, all stuff for my steering wheel runs on windows). After a longer time, I tried it again and it worked with no problems. I've tested the old shell script version and python edition, and both worked without problems.
It could be your kernel version (because for me, nothing other really changed than the kernel), can you post your version? It's just a guess, because I really don't know it.

**Comment by Joggingbrot551** [comment] 2020-01-19 16:06
I switched to Manjaro Linux no it runs without issues. That fixed it for me, so I can't look up the Xubuntu Kernel Version any more.

**Comment by Lucki** [comment] 2020-04-28 17:15
@kakurasan IMHO we should close this as it's likely not our fault or anything we can do about besides saying to keep everything up2date (kernel, wine/proton, truckersmp) and keep trying again once in a while.

**Comment by kakurasan** [comment] 2020-04-29 03:19
@Lucki That's true. I, too, think so.

**Closed by kakurasan** 2020-04-29 03:19 UTC
