### ISSUE TITLE
client protocol version does not match

### ISSUE THREAD

**Issue by swipis** [lhark/truckersmp-cli#15] opened 2018-02-02 08:05 UTC
Hello, I guess this is not truckersmp-cli problem, but I cannot connect to the servers, ingame chat I got message "Cannot connect to server. Your client protocol not match with the server.". I tried to redownload client  and truckersmp-cli but no luck. Any clew what to do?

I noticed when I first time started truckersmp-cli it downloaded some files, any posible way to update files?

Thank you

**Comment by lhark** [comment] 2018-02-02 16:18
I cannot reproduce the problem on my side. Have you tried connecting to different servers (Europe 1, 2 or 3 for example) ?

Every time you launch truckersmp-cli, it checks for updates of the mod. You should also make sure the game itself is up to date in Steam.

If you provide all the commands you entered and the full output of the script, I might be able to get a clearer understanding of the issue.

**Comment by swipis** [comment] 2018-02-02 19:44
Yes same on all servers (I was playing mp and just 2 days ago this happens), commands is `WINEPREFIX=~/ets2mp ./truckersmp-cli /home/swipis/ets2mp/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Euro\ Truck\ Simulator\ 2/`
and the output is
`--2018-02-02 19:38:40--  https://update.ets2mp.com/files.json
Resolving update.ets2mp.com... 104.24.114.213, 104.24.115.213, 2400:cb00:2048:1::6818:73d5, ...
Connecting to update.ets2mp.com|104.24.114.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘STDOUT’

-                       [ <=>                ]   2.34K  --.-KB/s    in 0s      

2018-02-02 19:38:41 (18.1 MB/s) - written to stdout [2395]


###################################################################
#                                                                 #
#  Please check that steam is running or the launcher won't work  #
#                                                                 #
###################################################################

Press enter if you are good to go:

  _______              _                 __  __ _____
 |__   __|            | |               |  \/  |  __ \
    | |_ __ _   _  ___| | _____ _ __ ___| \  / | |__) |
    | | '__| | | |/ __| |/ / _ \ '__/ __| |\/| |  ___/
    | | |  | |_| | (__|   <  __/ |  \__ \ |  | | |
    |_|_|   \__,_|\___|_|\_\___|_|  |___/_|  |_|_|

[19:40:00] <info> [p3api] Game version is supported. Base address: 0000000000000000 Signature: 98df145019dc
[19:40:00] <info> [net] [http async] Creating thread(s)[1]...
[19:40:00] <info> [net] [http async] Thread(s) created.
[19:40:00] <info> [client] Initialized successfully.
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198016483161 [API loaded no]
[19:40:06] <info> [gl] Display init.
[19:40:06] <info> [gl] OpenGL version: 3.3.0 NVIDIA 390.25 [3.3] Using: core
[19:40:06] <info> [inp] Keyboard input initialized. Input resolution = 1920x1080.
[19:40:06] <info> [gl] Device initialized.
[19:40:07] <info> [inp] Mouse input initialized.
[19:40:07] <info> Game started
before paHostApiInitializers[0].
after paHostApiInitializers[0].
[19:40:07] <info> [codec] Initialization succeed
[19:40:07] <info> [cb_radio] Microphone initialized! : Wine Sound Mapper - Input / MME
[19:40:07] <info> [cb_radio] Speaker initialized! : Wine Sound Mapper - Output
[19:40:20] <info> SteamID: 76561198016483161
[19:40:37] <info> [net] Connecting to 163.172.64.173:42861.`
and then loads of this error, but game works fine (red color OFFLINE in the corner)
`[19:40:48] <error> [gl] glGetError returned error!`

**Comment by lhark** [comment] 2018-02-02 20:43
I have honestly no idea what is causing the problem. I tried launching the game using OpenGL like your installation seems to be configured to do and everything went flawlessly. The only difference I see is that your driver is slightly newer than mine NVIDIA 390.25 vs 387.34. You could try running the game with directX : right click the game on steam and chose "Lauch with DirectX (64-bit)", then you can close it and launch the mod once again with truckersmp-cli. But I doubt it will change anything.

If you know how, you could also try to inspect the network requests and see if you don't have something blocking the requests on your  network.

Also, depending on where you live, you might be impacted by this maintenance : https://forum.truckersmp.com/index.php?/topic/59602-server-downtime/

**Comment by swipis** [comment] 2018-02-02 20:57
I tried OpenGl and DirectX options but same output. What about drivers MP was working 2 days ago no problem... Ahh well... If I delete truckermp (with all dll's) folder should script download again automatically?

**Comment by lhark** [comment] 2018-02-02 21:01
Yes, truckersmp-cli will update everything. Try that but keep in mind it might also be a network issue, because the mod seems to work correctly (the red messages in game are implemented by the mod).

**Comment by swipis** [comment] 2018-02-02 21:03
I deleted that folder and then I getting some core dll is missing but no download.

**Comment by lhark** [comment] 2018-02-02 21:06
Hmm, strange, try deleting **files.json**, and if it is still there, **.checksums**.

**Comment by swipis** [comment] 2018-02-02 21:13
downlloaded just **files.json** and new folder is created but that about it.
`unable to locate library (./truckersmp\core_ets2mp.dll).`

**Comment by lhark** [comment] 2018-02-02 21:22
Do you have the latest version of truckersmp-cli ? There was a problem a few weeks ago with the download servers which has since been fixed.

**Comment by swipis** [comment] 2018-02-02 21:25
yes downloaded twice yesterday

**Comment by lhark** [comment] 2018-02-02 21:26
Can I have the logs you get when you try to download a new version ? BTW, next time to keep a backup, just rename the truckersmp folder to something like truckersmp.bak.

**Comment by swipis** [comment] 2018-02-02 21:29
where can I find these logs?

**Comment by lhark** [comment] 2018-02-02 21:30
I mean the output in the console, same thing you posted before.

**Comment by swipis** [comment] 2018-02-02 21:31
[client_02_02_2018.log](https://github.com/lhark/truckersmp-cli/files/1690895/client_02_02_2018.log)

**Comment by lhark** [comment] 2018-02-02 21:35
I'm more interested by the part at the beginning where truckersmp-cli tries to update the files. Can you get the output from the moment you run the command ?

**Comment by swipis** [comment] 2018-02-02 21:45
thats all output what I getting:
```
WINEPREFIX=~/ets2mp ./truckersmp-cli /home/swipis/ets2mp/drive_c/Program\ Files\ \(x86\)/Steam/steamapps/common/Euro\ Truck\ Simulator\ 2/
--2018-02-02 21:33:00--  https://update.ets2mp.com/files.json
Resolving update.ets2mp.com... 104.24.115.213, 104.24.114.213, 2400:cb00:2048:1::6818:73d5, ...
Connecting to update.ets2mp.com|104.24.115.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘STDOUT’

-                                [ <=>                                        ]   2.37K  --.-KB/s    in 0s      

2018-02-02 21:33:00 (22.6 MB/s) - written to stdout [2427]


#################################################################                                                      #
#  Please check that steam is running or the launcher won't work  #
#                                                                 #
#################################################################

```

**Comment by lhark** [comment] 2018-02-02 21:49
Could you share the **files.json** you have, and also try to open https://update.ets2mp.com/files.json in your web browser ?

**Comment by swipis** [comment] 2018-02-02 21:50
files.json (sorry can't drop this file here)
[files.zip](https://github.com/lhark/truckersmp-cli/files/1690944/files.zip)

**Comment by lhark** [comment] 2018-02-02 21:56
It's strange, it seems you received the json in compressed form. What does it look like when you access the URL in your browser ?

**Comment by swipis** [comment] 2018-02-02 21:58
no I compressed because I cant drop in here this **file.json** file. and in browser it looks like:

```
Files |  
-- | --
0 |  
FilePath | "/licenses/bullet_LICENSE.txt"
Md5 | "919d53b5b1fc164511ceb288135a680e"
Type | "system"
```

**Comment by lhark** [comment] 2018-02-02 21:58
Also can you copy the result of the following command here:
`wget --version`

**Comment by lhark** [comment] 2018-02-02 22:01
I understand you compressed it inside a zip archive, but the **files.json** itself is compressed. When you open it in a text editor, does it look like text or just a binary mess ?

**Comment by swipis** [comment] 2018-02-02 22:02
mess

**Comment by lhark** [comment] 2018-02-02 22:14
Do you have a **~/.wgetrc** in your home with something like `header = Accept-Encoding: gzip,deflate` inside ?

Could you try manually downloading **files.json** using the following command
`wget --header 'Accept-encoding: identity' -O - "https://update.ets2mp.com/files.json" > files-test.json`
and check if the response is still binary ?

**Comment by swipis** [comment] 2018-02-03 08:20
no I dont have this folder

**Closed** 2018-02-03 15:48 UTC

**Comment by lhark** [comment] 2018-02-03 15:50
This should solve solve your problem, now the launcher will update your files correctly.
