### ISSUE TITLE
Cant install.

### ISSUE THREAD

**Issue by ultimatecompbg** [lhark/truckersmp-cli#17] opened 2018-04-15 19:43 UTC
This isnt exactly a issue, but its important to ask.
When i try to install the launcher, it gives me:

###################################################################
#                                                                 #
#  Please check that steam is running or the launcher won't work  #
#                                                                 #
###################################################################

Press enter if you are good to go:
./truckersmp-cli: 58: read: arg count
wine: created the configuration directory '/home/ultimatecompbg/Downloads'
wine: configuration in '/home/ultimatecompbg/Downloads' has been updated.
CreateProcess("/home/ultimatecompbg/.steam/steam/SteamApps/common/Euro\bin\win_x64\eurotrucks2.exe -nointro -64bit") failed; error code = 0x00000002

ultimatecompbg@ultimatecompbg ~/Свалени/truckersmp-cli-master $ 

My steam is running, and it should be right but it isnt.
Thanks in advance for help.

**Comment by lhark** [comment] 2018-04-15 20:09
It looks like you didn't escape the path to the game folder correctly, try putting it between single quotes (') like so:
`./truckersmp-cli '/home/ultimatecompbg/.steam/steam/SteamApps/common/Euro Truck Simulator 2'`
I'll close for now as the issue looks the same as #5.

**Comment by lhark** [comment] 2018-04-15 21:32
Could post the result of those commands ?
`ls -lha '/home/ultimatecompbg/.steam/steam/SteamApps/common/Euro Truck Simulator 2'`
and
`ls -lha '/home/ultimatecompbg/.steam/steam/SteamApps/common/Euro Truck Simulator 2/bin/win_x64'`
The error code **0x00000002** mean "file not found" so I'm wondering if there is an error in the path you gave or if the game is correctly installed. Can you run the singleplayer game with wine in Steam ?

**Comment by ultimatecompbg** [comment] 2018-04-15 22:03
I am using Linux version.
I will try tomorrow.

**Comment by lhark** [comment] 2018-04-15 22:11
The mod TruckersMP only officially supports windows. The goal of this launcher is to allow you to launch the mod using wine (because the official launcher ~~is garbage~~ doesn't run with wine)

**Comment by ultimatecompbg** [comment] 2018-04-16 17:00
Hello. I now this isn`t a issue but i dont know were to ask.
It`s what gives me when install windows steam and open steam with wine:
fixme:winsock:WSAIoctl SIO_GET_EXTENSION_FUNCTION_POINTER: unimplemented DisconnectEx
\src\common\net.cpp (263) : Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045)
\src\common\net.cpp (263) : Fatal assert failed: c:\buildslave\steam_rel_client_win32\build\src\common\net.cpp, line 263.  Application exiting.

Assert( Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045) ):c:\buildslave\steam_rel_client_win32\build\src\common\net.cpp:263

fixme:advapi:EventRegister {47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f006de0, 0x3f0491e0, 0x3f0491d8
fixme:advapi:EventRegister {58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f006de0, 0x3f049218, 0x3f049210
fixme:advapi:EventRegister {3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f006de0, 0x3f0491a8, 0x3f0491a0
fixme:advapi:EventRegister {1432afee-73b0-42ce-9821-7e134361b433}, 0x3f006de0, 0x3f049250, 0x3f049248
fixme:advapi:EventRegister {4372afee-73b0-42ce-9821-7e134361b519}, 0x3f006de0, 0x3f049288, 0x3f049280
fixme:dbghelp:elf_search_auxv can't find symbol in module
_ExitOnFatalAssert
fixme:advapi:EventUnregister deadbeef: stub
Sorry for the anxiety and thanks in advance for help!

**Comment by lhark** [comment] 2018-04-16 17:52
I don't know which distro, or wine version you are running, but if you are having trouble setting up wine, you could use something like [lutris](https://lutris.net/downloads/) that will take care of everything for you. They even have an installer that uses truckersmp-cli : https://lutris.net/games/euro-truck-simulator-2/

**Comment by ultimatecompbg** [comment] 2018-04-16 19:44
I installed Steam and Ets2, it works all perfect. But the problem is i have no idea how to run truckersmp. I tried with normal truckersmp, but when i click it it dont do anything. I tried with truckersmp-cli but when i enter the command it only gives " >    "

**Comment by lhark** [comment] 2018-04-16 20:02
Usually, when the shell gives you "> ", it's often you have a quote (' or ") that's not escaped correctly. Also, be careful, ' and \` don't have the same meaning: the first one allows you to quote literal strings, the latter is used to run a subcommand. I don't know how easy both are to access on a cyrillic keyboard though.

You could post the exact command you tried to run.

**Comment by ultimatecompbg** [comment] 2018-04-16 20:10
WINEPREFIX=~/wine64 ./truckersmp-cli /home/ultimatecompbg/PlayOnLinux's virtual drives/Steam/drive_c/Program Files/Steam/steamapps/common/Euro Truck Simulator 2

**Comment by ultimatecompbg** [comment] 2018-04-16 20:27
2018-04-16 23:26:38 (311 KB/s) - written to stdout [14419/14419]


###################################################################
#                                                                 #
#  Please check that steam is running or the launcher won't work  #
#                                                                 #
###################################################################

Press enter if you are good to go:
./truckersmp-cli: 58: read: arg count

**Comment by ultimatecompbg** [comment] 2018-04-16 20:28
Steam was running.

**Comment by lhark** [comment] 2018-04-16 20:39
And... what happened ?

BTW I pushed a fix for the `./truckersmp-cli: 58: read: arg count` if you want to download the last version.

**Comment by ultimatecompbg** [comment] 2018-04-16 20:41
Nothing. It stopped here.

**Comment by lhark** [comment] 2018-04-16 21:13
Have you tried with the latest version ?

**Comment by lhark** [comment] 2018-04-16 21:59
First, make sure you are running steam with the same wine prefix as truckersmp-cli.
```
WINEPREFIX=~/wine64 WINEARCH=win64 wine "/home/ultimatecompbg/PlayOnLinux's virtual drives/Steam/drive_c/Program Files/Steam/Steam.exe"
```
Then could you try to run the following command:
```
WINEPREFIX=~/wine64 WINEARCH=win64 wine "./truckersmp-cli.exe" "/home/ultimatecompbg/PlayOnLinux's virtual drives/Steam/drive_c/Program Files/Steam/steamapps/common/Euro Truck Simulator 2" "./truckersmp"
```

**Comment by ultimatecompbg** [comment] 2018-04-16 22:14
Im sure this is the problem, but when i run Steam from terminal it gives me``

> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
fixme:winsock:WSAIoctl SIO_GET_EXTENSION_FUNCTION_POINTER: unimplemented DisconnectEx
\src\common\net.cpp (263) : Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045)
\src\common\net.cpp (263) : Fatal assert failed: c:\buildslave\steam_rel_client_win32\build\src\common\net.cpp, line 263.  Application exiting.

Assert( Fatal Assertion Failed: PlatformSocketsInit failed, error [no name available] (10045) ):c:\buildslave\steam_rel_client_win32\build\src\common\net.cpp:263

fixme:dbghelp:elf_search_auxv can't find symbol in module
_ExitOnFatalAssert

When i run it from PlayOnLinux->Steam->Run it runs no problem

**Comment by lhark** [comment] 2018-04-16 22:40
What version of wine do you have installed ? `wine --version`
Try the same commands as before, but replace `WINEPREFIX=~/wine64` with `WINEPREFIX="/home/ultimatecompbg/PlayOnLinux's virtual drives/Steam"`.

**Comment by ultimatecompbg** [comment] 2018-04-17 08:15
1.6.2

**Comment by lhark** [comment] 2018-04-17 15:51
Your wine version is ancient, it might still work, but I can't guarantee anything.
Also it's now pretty clear the issue is with your setup and not with truckersmp-cli.
You said steam works with PlayOnLinux, great, run steam with PlayOnLinux then. Now you need to figure out which wine prefix it is using (if I had to guess: `"/home/ultimatecompbg/PlayOnLinux's virtual drives/Steam"`). Once you know the prefix, all you need to do is launch truckersmp-cli with the same prefix.

Or you could use the Lutris installer which is objectively better than PlayOnLinux: https://lutris.net/games/euro-truck-simulator-2/

**Closed by lhark** 2018-04-17 15:51 UTC

**Comment by ultimatecompbg** [comment] 2018-04-17 17:04
Cannot mount required file: /truckersmp/data/ets2/mods/data1.mp..

**Comment by lhark** [comment] 2018-04-18 05:51
1) We've established that this doesn't concern this repository. For your problems with Lutris, the forums are this way: https://forums.lutris.net/c/support
2) Don't forget, on the forums, to provide context and explanations with your questions.
I won't be answering any more questions on this issue since my time is limited and this has nothing to do with my repository. Good luck with your inquiries!

**Comment by ultimatecompbg** [comment] 2018-04-18 08:34
I dont used lutris.
Okay, np
