### ISSUE TITLE
TruckersMP Not Working 

### ISSUE THREAD

**Issue by Netinho1109** [lhark/truckersmp-cli#92] opened 2020-06-28 17:06 UTC
I did the same process that two weeks ago has not worked Notes:
 I reinstalled the OS

Success! App '227300' fully installed.
** DEBUG **  Updating mod files
** DEBUG **  No files to download
./truckersmp-cli -eup -n netinho1109 -vv -g  -o  -x   46,50s user 6,93s system 26% cpu 3:22,86 total
manoel@archlinux ~/truckersmp-cli (git)-[master] % ./truckersmp-cli -esp -vv -g "/home/manoel/.local/share/Steam/steamapps/common/Euro Truck Simulator 2" -o "/home/manoel/.local/share/Steam/steamapps/common/Proton 5.0" -x "/home/manoel/.local/share/Steam/steamapps/compatdata/227300"
** DEBUG **  No moddir set, setting to default
** INFO **  Mod directory: /home/manoel/.local/share/truckersmp-cli/TruckersMP
** INFO **  AppID/GameID: 227300 (ets2)
** INFO **  Game directory: /home/manoel/.local/share/Steam/steamapps/common/Euro Truck Simulator 2
** INFO **  Prefix: /home/manoel/.local/share/Steam/steamapps/compatdata/227300
** INFO **  Proton directory: /home/manoel/.local/share/Steam/steamapps/common/Proton 5.0
** DEBUG **  Updating mod files
** DEBUG **  No files to download
** DEBUG **  Starting game with Proton
** DEBUG **  Starting Steam...
                                                                      
** DEBUG **  Steam should now be up and running and the user logged in.
** INFO **  Steam installation directory: /home/manoel/.local/share/Steam
** INFO **  Startup command:
  SteamGameId=227300
  SteamAppId=227300
  STEAM_COMPAT_DATA_PATH=/home/manoel/.local/share/Steam/steamapps/compatdata/227300
  STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/manoel/.local/share/Steam
  PROTON_USE_WINED3D=0
  PROTON_NO_D3D11=1
  LD_PRELOAD=/home/manoel/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so
  /usr/bin/python3 /home/manoel/.local/share/Steam/steamapps/common/Proton 5.0/proton
  run
  /home/manoel/truckersmp-cli/truckersmp_cli/truckersmp-cli.exe /home/manoel/.local/share/Steam/steamapps/common/Euro Truck Simulator 2 /home/manoel/.local/share/truckersmp-cli/TruckersMP
** INFO **  Proton output:
ERROR: ld.so: object '/home/manoel/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/manoel/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
esync: up and running.
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Setting breakpad minidump AppID = 227300
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198115254865 [API loaded no]
pid 147572 != 147571, skipping destruction (fork without exec?)

**Comment by Lucki** [comment] 2020-06-28 18:12
Does `/home/manoel/truckersmp-cli/truckersmp_cli/truckersmp-cli.exe` exist?

**Comment by Netinho1109** [comment] 2020-06-28 19:09
I didn't find this file.

What I found there was the following: __init__.py  proton.json __pycache__

**Comment by Lucki** [comment] 2020-06-28 23:12
Duplicate of #88 

https://github.com/lhark/truckersmp-cli#build

**Closed by Lucki** 2020-06-28 23:12 UTC
